# Nom de l'application
spring.application.name=ebanking

# ================= Database =================
spring.datasource.url=jdbc:postgresql://localhost:5432/ebanking
spring.datasource.username=postgres
spring.datasource.password=Justin
spring.datasource.driver-class-name=org.postgresql.Driver

# ================= JPA / Hibernate =================
spring.jpa.hibernate.ddl-auto=update  
spring.jpa.show-sql= true            
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ================= Server =================
# port où ton app sera accessible
server.port=8081
server.address=0.0.0.0
debug=true
#logging.level.org.springframework.web=DEBUG
#logging.level.com.bank.ebanking=DEBUG

spring.security.user.name=admin
spring.security.user.password=admin123
